//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Administrative_Financial_Process
    {
        public string CR_Mas_Sup_Administrative_Financial_Process_Code { get; set; }
        public string CR_Mas_Sup_Administrative_Financial_Process_Type { get; set; }
        public string CR_Mas_Sup_Administrative_Financial_Process_Ar_Name { get; set; }
        public string CR_Mas_Sup_Administrative_Financial_Process_En_Name { get; set; }
        public string CR_Mas_Sup_Administrative_Financial_Process_Fr_Name { get; set; }
        public Nullable<int> CR_Mas_Sup_Default_Value_Follow_Up_Alarm_Befor_KM { get; set; }
        public Nullable<int> CR_Mas_Sup_Default_Value_Follow_Up_Alarm_Befor_Day { get; set; }
        public Nullable<int> CR_Mas_Sup_Default_Value_Follow_Up_KM { get; set; }
        public Nullable<int> CR_Mas_Sup_Default_Value_Follow_Up { get; set; }
        public string CR_Mas_Sup_Administrative_Financial_Process_Status { get; set; }
        public string CR_Mas_Sup_Administrative_Financial_Process_Reasons { get; set; }
    }
}
