//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Color
    {
        public string CR_Mas_Sup_Color_Code { get; set; }
        public string CR_Mas_Sup_Color_Group_Code { get; set; }
        public string CR_Mas_Sup_Color_Ar_Name { get; set; }
        public string CR_Mas_Sup_Color_En_Name { get; set; }
        public string CR_Mas_Sup_Color_Fr_Name { get; set; }
        public string CR_Mas_Sup_Color_Status { get; set; }
        public string CR_Mas_Sup_Color_Reasons { get; set; }
    
        public virtual CR_Mas_Sup_Group CR_Mas_Sup_Group { get; set; }
    }
}
