//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Employer
    {
        public string CR_Mas_Sup_Employer_Code { get; set; }
        public string CR_Mas_Sup_Employer_Group_Code { get; set; }
        public string CR_Mas_Sup_Employer_Sector_Code { get; set; }
        public string CR_Mas_Sup_Employer_Ar_Name { get; set; }
        public string CR_Mas_Sup_Employer_En_Name { get; set; }
        public string CR_Mas_Sup_Employer_Fr_Name { get; set; }
        public Nullable<int> CR_Mas_Sup_Employer_Counter { get; set; }
        public string CR_Mas_Sup_Employer_Status { get; set; }
        public string CR_Mas_Sup_Employer_Reasons { get; set; }
    
        public virtual CR_Mas_Sup_Group CR_Mas_Sup_Group { get; set; }
        public virtual CR_Mas_Sup_Sector CR_Mas_Sup_Sector { get; set; }
    }
}
