//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_City
    {
        public string CR_Mas_Sup_City_Code { get; set; }
        public string CR_Mas_Sup_City_Group_Code { get; set; }
        public string CR_Mas_Sup_City_Ar_Name { get; set; }
        public string CR_Mas_Sup_City_En_Name { get; set; }
        public string CR_Mas_Sup_City_Fr_Name { get; set; }
        public string CR_Mas_Sup_City_Status { get; set; }
        public string CR_Mas_Sup_City_Reasons { get; set; }
        public string CR_Mas_Sup_City_Regions_Code { get; set; }
    
        public virtual CR_Mas_Sup_Regions CR_Mas_Sup_Regions { get; set; }
        public virtual CR_Mas_Sup_Group CR_Mas_Sup_Group { get; set; }
    }
}
