//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sup_Brand()
        {
            this.CR_Mas_Sup_Model = new HashSet<CR_Mas_Sup_Model>();
        }
    
        public string CR_Mas_Sup_Brand_Code { get; set; }
        public string CR_Mas_Sup_Brand_Ar_Name { get; set; }
        public string CR_Mas_Sup_Brand_En_Name { get; set; }
        public string CR_Mas_Sup_Brand_Fr_Name { get; set; }
        public string CR_Mas_Sup_Brand_Status { get; set; }
        public string CR_Mas_Sup_Brand_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Sup_Model> CR_Mas_Sup_Model { get; set; }
    }
}
