//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Com_Supporting
    {
        public string CR_Mas_Com_Supporting_Code { get; set; }
        public string CR_Mas_Com_Supporting_Type { get; set; }
        public string CR_Mas_Com_Supporting_Ar_Long_Name { get; set; }
        public string CR_Mas_Com_Supporting_Ar_Short_Name { get; set; }
        public string CR_Mas_Com_Supporting_En_Long_Name { get; set; }
        public string CR_Mas_Com_Supporting_En_Short_Name { get; set; }
        public string CR_Mas_Com_Supporting_Tax_Number { get; set; }
        public string CR_Mas_Com_Supporting_Status { get; set; }
        public string CR_Mas_Com_Supporting_Reasons { get; set; }
    }
}
