//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_User_Sub_Validation
    {
        public string CR_Mas_User_Sub_Validation_Code { get; set; }
        public string CR_Mas_User_Sub_Validation_Tasks_Code { get; set; }
        public Nullable<bool> CR_Mas_User_Sub_Validation_Insert { get; set; }
        public Nullable<bool> CR_Mas_User_Sub_Validation_UpDate { get; set; }
        public Nullable<bool> CR_Mas_User_Sub_Validation_Delete { get; set; }
        public Nullable<bool> CR_Mas_User_Sub_Validation_UnDelete { get; set; }
        public Nullable<bool> CR_Mas_User_Sub_Validation_Hold { get; set; }
        public Nullable<bool> CR_Mas_User_Sub_Validation_UnHold { get; set; }
        public Nullable<bool> CR_Mas_User_Sub_Validation_Print { get; set; }
    
        public virtual CR_Mas_User_Information CR_Mas_User_Information { get; set; }
    }
}
