//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Social
    {
        public string CR_Mas_Sup_Social_Code { get; set; }
        public string CR_Mas_Sup_Social_Group_Code { get; set; }
        public string CR_Mas_Sup_Social_Ar_Name { get; set; }
        public string CR_Mas_Sup_Social_En_Name { get; set; }
        public string CR_Mas_Sup_Social_Fr_Name { get; set; }
        public string CR_Mas_Sup_Social_Status { get; set; }
        public string CR_Mas_Sup_Social_Reasons { get; set; }
    
        public virtual CR_Mas_Sup_Group CR_Mas_Sup_Group { get; set; }
    }
}
