//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_User_Information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_User_Information()
        {
            this.CR_Mas_User_Main_Validation = new HashSet<CR_Mas_User_Main_Validation>();
            this.CR_Mas_User_Sub_Validation = new HashSet<CR_Mas_User_Sub_Validation>();
        }
    
        public string CR_Mas_User_Information_Code { get; set; }
        public string CR_Mas_User_Information_PassWord { get; set; }
        public string CR_Mas_User_Information_Ar_Name { get; set; }
        public string CR_Mas_User_Information_En_Name { get; set; }
        public string CR_Mas_User_Information_Fr_Name { get; set; }
        public string CR_Mas_User_Information_Mobile_No { get; set; }
        public string CR_Mas_User_Information_Status { get; set; }
        public string CR_Mas_User_Information_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_User_Main_Validation> CR_Mas_User_Main_Validation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_User_Sub_Validation> CR_Mas_User_Sub_Validation { get; set; }
    }
}
