//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sys_Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sys_Tasks()
        {
            this.CR_Mas_User_Main_Validation = new HashSet<CR_Mas_User_Main_Validation>();
            this.CR_Mas_Msg_Questions_Answer = new HashSet<CR_Mas_Msg_Questions_Answer>();
        }
    
        public string CR_Mas_Sys_Tasks_Code { get; set; }
        public string CR_Mas_Sys_System_Code { get; set; }
        public string CR_Mas_Sys_Tasks_Ar_Name { get; set; }
        public string CR_Mas_Sys_Tasks_En_Name { get; set; }
        public string CR_Mas_Sys_Tasks_Fr_Name { get; set; }
        public string CR_Mas_Sys_Tasks_Status { get; set; }
        public string CR_Mas_Sys_Tasks_Reasons { get; set; }
        public Nullable<bool> CR_Mas_Sys_Tasks_Main_Validation { get; set; }
        public Nullable<bool> CR_Mas_Sys_Tasks_Sub_Validation { get; set; }
    
        public virtual CR_Mas_Sys_System_Name CR_Mas_Sys_System_Name { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_User_Main_Validation> CR_Mas_User_Main_Validation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Msg_Questions_Answer> CR_Mas_Msg_Questions_Answer { get; set; }
    }
}
