//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sup_Group()
        {
            this.CR_Mas_Sup_City = new HashSet<CR_Mas_Sup_City>();
            this.CR_Mas_Sup_Model = new HashSet<CR_Mas_Sup_Model>();
            this.CR_Mas_Sup_Category_Car = new HashSet<CR_Mas_Sup_Category_Car>();
            this.CR_Mas_Sup_Color = new HashSet<CR_Mas_Sup_Color>();
        }
    
        public string CR_Mas_Sup_Group_Code { get; set; }
        public string CR_Mas_Sup_Group_Ar_Name { get; set; }
        public string CR_Mas_Sup_Group_En_Name { get; set; }
        public string CR_Mas_Sup_Group_Fr_Name { get; set; }
        public Nullable<bool> CR_Mas_Sup_Group_Classified_Data { get; set; }
        public Nullable<bool> CR_Mas_Sup_Group_Independent_Data { get; set; }
        public string CR_Mas_Sup_Group_Status { get; set; }
        public string CR_Mas_Sup_Group_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Sup_City> CR_Mas_Sup_City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Sup_Model> CR_Mas_Sup_Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Sup_Category_Car> CR_Mas_Sup_Category_Car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Sup_Color> CR_Mas_Sup_Color { get; set; }
    }
}
