//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Registration_Car
    {
        public string CR_Mas_Sup_Registration_Car_Code { get; set; }
        public string CR_Mas_Sup_Registration_Car_Ar_Name { get; set; }
        public string CR_Mas_Sup_Registration_Car_En_Name { get; set; }
        public string CR_Mas_Sup_Registration_Car_Fr_Name { get; set; }
        public string CR_Mas_Sup_Registration_Car_Status { get; set; }
        public string CR_Mas_Sup_Registration_Car_Reasons { get; set; }
    }
}
