//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Car_Features
    {
        public string CR_Mas_Sup_Car_Features_Code { get; set; }
        public string CR_Mas_Sup_Car_Features_Ar_Name { get; set; }
        public string CR_Mas_Sup_Car_Features_En_Name { get; set; }
        public string CR_Mas_Sup_Car_Features_Fr_Name { get; set; }
        public string CR_Mas_Sup_Car_Features_Status { get; set; }
        public string CR_Mas_Sup_Car_Features_Reasons { get; set; }
    }
}
