//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sys_Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sys_Tasks()
        {
            this.CR_Mas_User_Main_Validation = new HashSet<CR_Mas_User_Main_Validation>();
        }
    
        public string CR_Mas_Sys_Tasks_Code { get; set; }
        public string CR_Mas_Sys_System_Code { get; set; }
        public string CR_Mas_Sys_Tasks_Ar_Name { get; set; }
        public string CR_Mas_Sys_Tasks_En_Name { get; set; }
        public string CR_Mas_Sys_Tasks_Fr_Name { get; set; }
        public string CR_Mas_Sys_Tasks_Status { get; set; }
        public string CR_Mas_Sys_Tasks_Reasons { get; set; }
        public Nullable<bool> CR_Mas_Sys_Tasks_Main_Validation { get; set; }
        public Nullable<bool> CR_Mas_Sys_Tasks_Sub_Validation { get; set; }
    
        public virtual CR_Mas_Sys_System_Name CR_Mas_Sys_System_Name { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_User_Main_Validation> CR_Mas_User_Main_Validation { get; set; }
    }
}
