//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_User_Validation
    {
        public string CR_Mas_User_Validation_Code { get; set; }
        public string CR_Mas_User_Validation_Tasks_Code { get; set; }
        public Nullable<bool> CR_Mas_User_Validation_Validity_Access { get; set; }
        public Nullable<bool> CR_Mas_User_Validation_Validity_Insert { get; set; }
        public Nullable<bool> CR_Mas_User_Validation_Validity_UpDate { get; set; }
        public Nullable<bool> CR_Mas_User_Validation_Validity_Delete { get; set; }
        public Nullable<bool> CR_Mas_User_Validation_Validity_UnDelete { get; set; }
        public Nullable<bool> CR_Mas_User_Validation_Validity_Hold { get; set; }
        public Nullable<bool> CR_Mas_User_Validation_Validity_UnHold { get; set; }
        public Nullable<bool> CR_Mas_User_Validation_Validity_Print { get; set; }
    
        public virtual CR_Mas_Sys_Tasks CR_Mas_Sys_Tasks { get; set; }
    }
}
