//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Car_Features
    {
        public string CR_Mas_Sup_Car_Features_Code { get; set; }
        public string CR_Mas_Sup_Car_Features_Ar { get; set; }
        public string CR_Mas_Sup_Car_Features_En { get; set; }
        public string CR_Mas_Sup_Car_Features_Fr { get; set; }
        public string CR_Mas_Sup_Car_Features_Status { get; set; }
        public string CR_Mas_Sup_Car_Features_Reasons { get; set; }
    }
}
