//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Nationalities
    {
        public string CR_Mas_Sup_Nationalities_Code { get; set; }
        public string CR_Mas_Sup_Nationalities_Group_Code { get; set; }
        public string CR_Mas_Sup_Nationalities_Country_Code { get; set; }
        public string CR_Mas_Sup_Nationalities_Ar_Name { get; set; }
        public string CR_Mas_Sup_Nationalities_En_Name { get; set; }
        public string CR_Mas_Sup_Nationalities_Fr_Name { get; set; }
        public Nullable<int> CR_Mas_Sup_Nationalities_Counter { get; set; }
        public string CR_Mas_Sup_Nationalities_Status { get; set; }
        public string CR_Mas_Sup_Nationalities_Reasons { get; set; }
    
        public virtual CR_Mas_Sup_Country CR_Mas_Sup_Country { get; set; }
        public virtual CR_Mas_Sup_Group CR_Mas_Sup_Group { get; set; }
    }
}
