//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentCarDBEntities : DbContext
    {
        public RentCarDBEntities()
            : base("name=RentCarDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CR_Mas_Sup_City> CR_Mas_Sup_City { get; set; }
        public virtual DbSet<CR_Mas_Sup_Regions> CR_Mas_Sup_Regions { get; set; }
        public virtual DbSet<CR_Mas_Sup_Brand> CR_Mas_Sup_Brand { get; set; }
        public virtual DbSet<CR_Mas_Sup_Group> CR_Mas_Sup_Group { get; set; }
        public virtual DbSet<CR_Mas_Sup_Model> CR_Mas_Sup_Model { get; set; }
        public virtual DbSet<CR_Mas_Sys_System_Name> CR_Mas_Sys_System_Name { get; set; }
        public virtual DbSet<CR_Mas_Sys_Tasks> CR_Mas_Sys_Tasks { get; set; }
        public virtual DbSet<CR_Mas_User_Information> CR_Mas_User_Information { get; set; }
        public virtual DbSet<CR_Mas_Sup_Car_Features> CR_Mas_Sup_Car_Features { get; set; }
        public virtual DbSet<CR_Mas_Sup_Car_Specifications> CR_Mas_Sup_Car_Specifications { get; set; }
        public virtual DbSet<CR_Mas_User_Main_Validation> CR_Mas_User_Main_Validation { get; set; }
        public virtual DbSet<CR_Mas_User_Sub_Validation> CR_Mas_User_Sub_Validation { get; set; }
    }
}
